### ISSUE TITLE
Publish ARM64 images on the registry

### ISSUE THREAD

**Issue by mgrzybek** [metal-stack/releases#177]
I see two use cases:
1. Installing Metal Stack on ARM64-based SBCs.
2. Testing the Metal Stack on Apple M1 using native virtual machines.

For instance, two workarounds are possible:
1. Emulate x84_64 virtual machines on Apple M1, reducing performances.
2. Rebuild the whole containers using a dedicated CI/CD, consuming a lot of time.

```console
$ skopeo inspect docker://ghcr.io/metal-stack/masterdata-api | jq '.Architecture'                                                                          ~
"amd64"
$
```

**Comment by Gerrit91** [comment]
We've been discussing this issue in our planning meeting now and we are unsure if this is worth the effort. Our developers only run Linux notebooks and we would need to extend all CI pipelines to release more platforms. Also there are some projects where this could be difficult, i.e. the metal-hammer binary and metal-images. Do you have any specific use-cases relevant for production that would benefit from this?

**Comment by mgrzybek** [comment]
This is purely a lab/dev use case using ARM-based laptops.

**Comment by Gerrit91** [comment]
Okay. Feel invited to join our Slack Workspace if you would like to further discuss on this, maybe we can find a compromise.
