### ISSUE TITLE
csi-driver-lvm is missing

### ISSUE THREAD

**Issue by majst01** [metal-stack/releases#5]
dunno howto add a new artefact.

**Comment by Gerrit91** [comment]
You can do so by hand or even better add it to the metal-robot configuration, which is in our metal-deployment project in Gitlab. :)

**Comment by majst01** [comment]
needs to be added to the release vector and metal-robot needs to be adopted

**Comment by majst01** [comment]
metal-robot needs adoption

**Comment by Gerrit91** [comment]
We don't add it to the release vector because we do not use it in the GEPM.
