### ISSUE TITLE
Integration tests failing now and then

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/releases#7]
We get this error from time to time at the end of the tasks:

```
...
RTNETLINK answers: No such process
Check if SSH login to firewall works
kex_exchange_identification: read: Connection reset by peer
```

https://github.com/metal-stack/releases/runs/998699677

**Comment by Gerrit91** [comment]
I temporarily disabled the SSH test, which muted the problem for now.

**Comment by majst01** [comment]
duplicate of https://github.com/metal-stack/mini-lab/issues/37
